### ISSUE TITLE
I am unable to use data-table-component-extension with react-data-table-component. Without the extension, data is being displayed in table, when used "NO DATA TO DISPLAY" error.

### ISSUE THREAD

**Issue by suhasholla3** [barisates/react-data-table-component-extensions#11]

**Comment by barisates** [comment]
Can i see your code?

**Comment by suhasholla3** [comment]
import React from 'react'
import Data from './backupfile-sept21.json';
import DataTable from 'react-data-table-component';
import DataTableExtensions from 'react-data-table-component-extensions';
import './Report.css'


const adminTransactions = Data.Admin_Transactions;

const employees = Data.Employees;
const empMapIdName = {};
console.log(Object.keys(employees).forEach(key => {
    // console.log(key);
    // console.log(employees[key].name);
    
    empMapIdName[key] = employees[key].name;
    
}));
console.log(  
    Object.keys(adminTransactions).forEach(key =>{
    // console.log(key);
    // console.log(adminTransactions[key].employee_id);
    let tempObj =  adminTransactions[key];

   if(!(tempObj.employee_id in empMapIdName)){
    //  console.log('Stock Update');
    //  if(!(tempObj.employee_id === undefined)){
       adminTransactions[key]["employee_id"] = ""
    //  }
        // adminTransactions[tempObj].name = "No Value";   
  }
  else{
      if(tempObj.employee_id in empMapIdName){
        //   console.log(empMapIdName[tempObj.employee_id]);
     
// if(tempObj.employee_id !== undefined){
    adminTransactions[key]["employee_id"] = empMapIdName[tempObj.employee_id];
// }     
      }
  }
}
))

console.log(adminTransactions);


// RELATED CODE  STARTS HERE

 const columns = [
{name:'Date', selector:'date', sortable: true,},
{name:'Type',selector:'type', sortable: true,},
{name:'Employee Name',selector: 'employee_id', sortable: true,},
{name:'VDSL',selector:'vdsl', sortable: true,},
{name:'Huawei',selector:'huawei', sortable: true,},
{name:'Nokia',selector:'nokia', sortable: true,},
{name:'VDSL 100 MBPS',selector:'vdsl_100mbps', sortable: true,},
{name:'Cable DropWire',selector:'cable_copper_dropwire', sortable: true,},
{name:'Cable 10 Pair',selector:'cable_10_pairs', sortable: true,},
{name:'Cable 5 Pair',selector:'cable_5_pairs', sortable: true,},
{name:'Cable Indoor',selector:'cable_indoor', sortable: true,},
{name:'Cable Outdoor',selector:'cable_outdoor', sortable: true,},
{name:'Pole Anchor',selector:'pole_anchor', sortable: true,},
{name:'Patch Cord',selector:'patch_cord', sortable: true,},
{name:'Rosset',selector:'rosset', sortable: true,},
{name:'Module',selector:'module', sortable: true,},
{name:'Face Flat',selector:'face_flat', sortable: true,},

];

 const values = Object.keys(adminTransactions).map(i=> adminTransactions[i]);

 const tableData = {
   columns,
   values
 }

export class Home extends React.Component {
    render() {
        return (      
                  <>
                <h1> Inventory report Installation</h1>
      <div className="report-card">

     <DataTableExtensions {...tableData}>
     <DataTable
      title="Inventory Report(Installation)"
      columns ={columns}
      data = {values}
        defaultSortField="date"
        defaultSortAsc={false}
        pagination
        highlightOnHover     
      />
     </DataTableExtensions>
     
      
      </div>
      
  
            </>
           
        )
    }
}

export default Home

**Comment by barisates** [comment]
### Change the name of the variable 'values' to 'data';

const **values** = Object.keys(adminTransactions).map(i=> adminTransactions[i]);

const tableData = {
columns,
**values**
}

### And remove this lines;

 <DataTableExtensions {...tableData}>
 <DataTable
  title="Inventory Report(Installation)"
  **columns ={columns}
  data = {values}** 
    defaultSortField="date"
    defaultSortAsc={false}
    pagination
    highlightOnHover     
  />
 </DataTableExtensions>

**Comment by suhasholla3** [comment]
Thank You SO much for the help. 
Appreciations man !!!

By the way one last query, how to set custom name to the export files ?

**Comment by barisates** [comment]
Sorry, unfortunately, there is no such feature yet.
