### ISSUE TITLE
The CSS file is imported in distributed JS

### ISSUE THREAD

**Issue by marknorrapscm** [barisates/react-data-table-component-extensions#12]
The `index.css` file is being imported by `index.js` on line 3. This causes problems with frameworks like Next.js. See [**CSS Imported by a Dependency**](https://github.com/vercel/next.js/blob/master/errors/css-npm.md).

Ideally we'd have some CSS-in-JS solution so the CSS files does not need to be distributed at all, but failing that I've done a quick fix over at my [forked repo](https://github.com/marknorrapscm/react-data-table-component-extensions). I am currently using this in my project and it's working fine; the only difference is that the user has to specify the CSS import:

```
import "react-data-table-component-extensions/dist/index.css";
```

I have updated the README to show this. Other than that, all I have done is remove the import statement from `index.js` and ran a build.

I can go ahead and submit a pull request but it will require a major version release since it's a breaking change. Let me know what you think.

**Comment by barisates** [comment]
Thank you for the fix. I think you can go ahead and submit a pull request. I release the v1.5.0 version.

**Comment by barisates** [comment]
#13 issue solved.

new version released;
[https://www.npmjs.com/package/react-data-table-component-extensions/v/1.5.0](url)
