### ISSUE TITLE
Version not updated in package.json and versioning not adhering to Semver

### ISSUE THREAD

**Issue by marknorrapscm** [barisates/react-data-table-component-extensions#14]
There are two issues here:

1. The `package.json` is still showing version 1.4.1 rather than 1.5.0

2. The pull request that I made a week or two ago introduced a breaking change, so the version should have increased from 1.4.1 to 2.0. 

From the Semver docs:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards compatible manner, and

Since my change extracted the CSS from the `index.js` file and requires user to add the following line to their code:

```
import "react-data-table-component-extensions/dist/index.css";
```

...I consider this a breaking change, thus requiring a major version increase. 

I would submit a PR myself but it would be easier for the owner to just update it and go through whatever their NPM publish procedure is.

**Comment by barisates** [comment]
Sorry I forgot to commit the last changes. But I published it as v1.5.0 on npmjs 10 days ago.  [https://www.npmjs.com/package/react-data-table-component-extensions](url)
