### ISSUE TITLE
Export To Excel render include a html tag

### ISSUE THREAD

**Issue by fachryadhitya** [barisates/react-data-table-component-extensions#21]
Hi, I was just starting to export some table into .xls file and I got the html tag included in my .xls file

![image](https://user-images.githubusercontent.com/58819726/120888560-14336680-c623-11eb-957e-7a54be7c03cc.png)

Am i missing something in my code? Thanks!

**Comment by MorganaUzhgorod** [comment]
did you resolve this problem? 
I have this problem to.

**Comment by MorganaUzhgorod** [comment]
@fachryadhitya

**Comment by fachryadhitya** [comment]
> @fachryadhitya
> did you resolve this problem?
> I have this problem to.

Actually if you opened the file in the Ms. Excel app, the exported excel file is shown correctly
