### ISSUE TITLE
Search filter limited to 3 characters

### ISSUE THREAD

**Issue by rjpv123** [barisates/react-data-table-component-extensions#26]
Hello, thanks a lot for this very useful extension. Just wanted to ask if is there a way to make the filter work upon input of 1 or 2 characters only? I just noticed that it was not working when I input a two character word hence, I noticed that table search filter works only upon entry of minimum 3 characters.

Thanks in advance!

**Comment by barisates** [comment]
You can use the new feature "filterDigit". In this way, you can set how many digits the search will start with. Thank you.
