### ISSUE TITLE
Custom placeholder in the filter field...

### ISSUE THREAD

**Issue by alimovz** [barisates/react-data-table-component-extensions#7]
Hi,

Have done some digging around, but cannot find how to change the default placeholder in the filter filed "Filter Table". Is there a way to have it say, for example, "Search Orders"?

**Comment by barisates** [comment]
Hi,

Added default placeholder for the filter area as a prop. You can use "**filterPlaceholder**" prop for change default placeholder in the filter field. (don't forget to update the component, V1.4.1)

88e6d87b02636cc945556e23cb87926926358c60
