### ISSUE TITLE
Placeholder, filter desabled ?

### ISSUE THREAD

**Issue by stonestecnologia** [barisates/react-data-table-component-extensions#8]
Hello how are you ?
I would like to know, how do I disable the print button and change the filter placeholder, or disable the filter;
Can I use Brazilian Portuguese? (en-US)
Thank you

**Comment by barisates** [comment]
See the properties [https://github.com/barisates/react-data-table-component-extensions#properties](https://github.com/barisates/react-data-table-component-extensions#properties)
